### PR TITLE
MAID-1468 Changes in FAQ page

### PR DESCRIPTION
**Pull request by shankar2105**
Changes in FAQ page implemented.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/71)

### CODE REVIEW

**Comment by krishnaIndia** [comment]
<sup>**[app/js/app.js, line 1 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe.github.io/71#-K14IusZkqFUBVFH8ZFw)** ([raw file](https://github.com/maidsafe/maidsafe.github.io/blob/94db6a9bf85be48f6ec14a4e35c1e25fdd1b8e81/app/js/app.js#L1)):</sup>
Why are we ignoring rules?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe.github.io/71)

**Comment by krishnaIndia** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe.github.io/71)

**Comment by krishnaIndia** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe.github.io/71)

**Comment by shankar2105** [comment]
<sup>**[app/js/app.js, line 1 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe.github.io/71#-K14IusZkqFUBVFH8ZFw)** ([raw file](https://github.com/maidsafe/maidsafe.github.io/blob/94db6a9bf85be48f6ec14a4e35c1e25fdd1b8e81/app/js/app.js#L1)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe.github.io/71)

**Pull request merged**
