### PR TITLE
MAID-1117 remove qt job

### PR DESCRIPTION
**Pull request by ioptio**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/47)

### CODE REVIEW

**Comment by rossmuir** [comment]
test this please

**Comment by rossmuir** [comment]
test this please

**Comment by rossmuir** [comment]
test this please

**Comment by ioptio** [comment]
Grunt test? I did that.

**Comment by rossmuir** [comment]
Yeah - the PR should trigger CI and the results should be published back to the PR automatically - currently this is not working - the jobs are triggered but do not send the status back. The phrase above "test this please" triggers another CI run - sorry for the confusion - I was trying to boss about a machine not you @ioptio  ;-)

**Comment by ioptio** [comment]
Ah, got it! ;-)

**Comment by maidsafe-highfive** [comment]
Build Successful

**Comment by maidsafe-highfive** [comment]
Build Successful

**Pull request merged**
