### PR TITLE
In-progress, don't merge

### PR DESCRIPTION
**Pull request by ioptio**
PR so @NickLambert can easily view updates. Don't merge! :)

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/48)

### CODE REVIEW

**Comment by NickLambert** [comment]
Thanks @ioptio!

**Comment by maidsafe-highfive** [comment]
Build Successful

**Comment by krishnaIndia** [comment]
test this please

**Comment by krishnaIndia** [comment]
test this please

**Pull request closed without merging**
